name: Bug Report
description: File a bug report to trigger automated debugging swarm
title: "[BUG] "
labels: ["bug", "swarm-debug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug (this will trigger a debugging swarm with 5-8 specialized agents)
      placeholder: "Describe the issue in detail. The more information you provide, the better the debugging swarm can assist."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide environment details:
        - OS: [e.g. Ubuntu 20.04, macOS 12.0]
        - Browser: [e.g. Chrome 100, Safari 15]
        - DevPod Version: [e.g. 0.5.0]
        - Gemini Flow Version: [e.g. 2.0.0-alpha.1]
      value: |
        - OS: 
        - Browser: 
        - DevPod Version: 
        - Gemini Flow Version: 
    validations:
      required: false