name: Feature Request
description: Request a feature to trigger development swarm
title: "[FEATURE] "
labels: ["enhancement", "swarm-develop"]  
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see implemented (this will trigger a development swarm with 8-12 agents)
      placeholder: "Clearly describe the feature you want. Include any specific requirements or constraints."
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain the use case and why this feature would be valuable
      placeholder: "Describe how this feature would be used and what problem it solves."
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what would make this feature complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - Simple (1-3 days)
        - Medium (1-2 weeks)
        - Complex (2-4 weeks)
        - Major (1+ months)
      default: 1
    validations:
      required: false